config/routes.rb
Rails.application.routes.draw do
  get '/my_flashcards', to: "flashcards#my_flashcards"
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :tasks, only: %i[index show new create] do
    resources :flashcards, only: :index
    resources :assignment, only: %i[new create]
  end
  resources :users, only: :show
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :flashcard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assigment.rb
class Assigment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :flashcards, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments

  validates :title, :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :assignments, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :tasks, through: :assignments
  has_many :flashcards, through: :answers
  has_one_attached :photo

  def after_update
    redirect_to user_path(current_user)
  end

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/assigments_controller.rb
class AssigmentsController < ApplicationController
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @task = Task.find(params[:task_id])
    @flashcards = @task.flashcards
  end

  def my_flashcards
    @flashcards = Flashcard.first(9)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
    @tasks = Task.first(3)
    @flashcards = Flashcard.first(4)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flashcards/_flashcard.html.erb
<div class="card-h" style="width: 18rem;">
  <div class="flashcard-inner" data-controller="flip" data-flip-target="flipper" data-action="click->flip#flipCard">
		<div class="card-face card-face-front">
      <h3 class="card-title-fc"><%= flashcard.content %></h3>
		</div>
		<div class="card-face card-face-back">
			<div class="card-content">
				<div class="card-header">
					<img src="#" alt="" class="" />
				</div>
				<div class="card-body">
					<p class="card-text-fc"><%= flashcard.answer %></p>
				</div>
        <div id="image-div">
          <img src="<%= flashcard.image  %>" alt="">
        </div>
			</div>
		</div>
	</div>
</div>

app/views/flashcards/index.html.erb
<div class="container container-fc" data-controller="progress">
  <div id="instruccion">
    <p>Has click sobre la tarjeta.</p>
  </div>
  <div id="divProgress" class="col-6">
    <progress id="progressBar" max="100" value="<%= 100 / @task.flashcards.count %>" data-progress-target="bar"></progress>
  </div>
  <div id="carouselExampleControls" class="carousel slide" data-bs-interval=false>

    <div class="carousel-inner">

      <% @task.flashcards.each_with_index do |flashcard, index| %>
        <div class="carousel-item w-100 <%= index == 0 ? 'active' : "" %>">
          <%= render "flashcard", flashcard: flashcard %>
        </div>
      <% end %>

<%# El controller --> es el elemento padre %>
<%# El target --> es el querySelector %>
<%# El action --> es el EventListener %>

      <div >
      <p data-progress-target="number" class="d-none"><%= @task.flashcards.count %></p>
        <button class="carousel-control-prev d-none" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev" data-progress-target="negative" data-action="click->progress#substract">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next" data-progress-target="positive" data-action="click->progress#add">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>

    </div>
  </div>
  <div id="retroalimentacion">
    <span><i class="fa-regular fa-circle-check"></i></span>
    <h5 id="tarjetasVistas" data-progress-target="label"> Has revisado 1 de <%= @task.flashcards.count %> flashcards.</h5>
  </div>
</div>
<div id="barraMorada">
  <div>
    <a href="mailto:contacto@rapidoaprendo.me?subject=Reportar un error">
      <span>
        <i class="fa-regular fa-flag"></i>
      </span>
      <p>Reportar un error. </p>
    </a>
  </div>
</div>

app/views/flashcards/my_flashcards.html.erb
<div class="my-flashcards-container">
  <div class="my-flashcard-title">
    <h2>Flashcards</h2>
  </div>
    <div class="my-flashcards" data-controller="flashcard-index-color">
      <% @flashcards.each do | flashcard | %>
      <div class="anchor">
        <div class="my-flashcard">
          <div class="my-flashcard-title">
            <h5><%= flashcard.content %></h5>
          </div>
          <div class="my-flashcard-info">
            <p><%= flashcard.answer %></p>
          </div>
        </div>
      </div>
  <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RapidoAprendo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'https://res.cloudinary.com/luda9/image/upload/v1662479946/development/logo-rapido-aprendo_awk1ee.png' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render "shared/app-navbar" %>
  <% else %>
    <%= render "shared/navbar" %>
  <% end %>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dashboard-page">
  <div class="user-container">
    <div class="user-info">

      <div class="user-avatar">
      <% unless current_user.photo.attached? %>
        <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",  style:"width:200px;" %>
      <% else %>
        <%= cl_image_tag current_user.photo.key, style:"width:200px; height:200px" %>
      <% end %>
      </div>
      <div class="user-name">
        <h5><%= @user.first_name %> <%= @user.last_name %></h5>
      </div>
      <div class="doctor">
        <p>Doctor: Angel Ramirez Escobedo</p>
      </div>
      <div class="racha">
        <div class="racha-img">
          <img src="https://res.cloudinary.com/luda9/image/upload/v1662752745/development/calendar_2_yd79lt.png" alt="">
        </div>
        <div class="racha-title">
          <p>12 días de racha</p>
        </div>
        <div class="racha-botones">
          <%= link_to "Mi cuenta", user_path(current_user) %>
        </div>
      </div>
    </div>

  </div>

  <div class="todo-information">
    <div class="tasks-container">
      <div class="task-title">
        <h3>Tareas</h3>
      </div>
      <div class="app-cards" data-controller="tasks-cards">
        <% @tasks.each do |task| %>
          <%= link_to task_path(task), class:"link-cards" do %>
          <div class="app-card tasks-card-fondo">
            <div class="app-card-title">
              <h4><%= task.title %></h4>
            </div>
            <div class="app-card-info">
              <div class="white-background"></div>
              <p><%= task.details %></p>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="flashcards-container">
        <div class="flashcards-title">
          <h4>Flashcards diarias</h4>
        </div>
      <div class="flashcards-box">
        <div class="app-flashcards" data-controller="flashcard-color">
          <% @flashcards.each do | flashcard | %>
          <%= link_to my_flashcards_path do %>
          <div class="app-flashcard flashcard-fondo">
            <div class="app-flashcard-title">
              <h5><%= flashcard.content %></h5>
            </div>
            <div class="app-flashcard-info">
              <p><%= flashcard.answer %></p>
            </div>
          </div>
          <% end %>
          <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-page">
  <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector3_q9gpmn.png" class="icon-3d-uno" alt="">
  <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector4_nxpebi.png" class="icon-3d-dos " alt="">
  <div class="home-page-info">
    <div class="home-page-title">
      <h1>Plataforma educativa para <span>padres</span> y <span>logopedas</span> con fin de combatir el <span>rotacismo</span></h1>
    </div>
    <div class="home-page-subtitle">
      <p>Totalmente gratuita dedicada a combatir el incorrecto pronunciamiento de la letra r, ayudándolos con lecciones y terapeutas especializados</p>
    </div>
    <div class="home-page-button">
      <%= link_to "Registrarse", new_user_registration_path, class: "boton registrarse" %>
    </div>
  </div>
  <div class="home-page-image">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector5_fho84p.png" class="cuadricula" alt="">
    <img src="https://images.unsplash.com/photo-1617117206620-b01f2919ff86?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" class="kids-drawing-ra" alt="Kids drawing rapido aprendo">
  </div>
</div>
<div class="barra-insignias">
  <div class="insignias">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661895590/development/logoipsum-229_cjn3p9.svg" width="400px" height="300px">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661895591/development/logoipsum-231_l4mnvk.svg" width="400px" height="300px">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661895591/development/logoipsum-232_odvx4m.svg" width="400px" height="300px">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661895590/development/logoipsum-214_uonyic.svg" width="400px" height="300px">
  </div>
</div>
<div class="cards-page">
  <div class="cards-header">
    <div class="cards-title">
      <h4>Rápido aprendo es la unica plataforma en México que enfrenta a el rotacismo</h4>
    </div>
    <div class="cards-subtitle">
      <p>De manera gratuita y desde la comodidad de tu hogar</p>
    </div>
  </div>

  <div class="cards-home">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector2_ndeee0.png" class="circulo-rojo" alt="">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector9_dyxzlx.png" class="espiral-amarillo" alt="">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector1_ck4690.png" class="personaje" alt="">

    <div class="card-home">
      <div class="card-image">
          <img src="https://res.cloudinary.com/luda9/image/upload/v1662055105/development/image-icon_lgryp1.png" width="150px">
      </div>
      <div class="card-text">
        <p>Aprende y practica mediante fotos y videos para un <span>aprendizaje amigable</span></p>
      </div>
    </div>

    <div class="card-home">
      <div class="card-image">
        <img src="https://res.cloudinary.com/luda9/image/upload/v1661899778/development/monitor-icon_stnqsd.png" width="150px">
      </div>
      <div class="card-text">
        <p>Realiza tareas y actividades desde la <span>comodidad de tu casa</span></p>
      </div>
    </div>

    <div class="card-home">
      <div class="card-image">
        <img src="https://res.cloudinary.com/luda9/image/upload/v1661899778/development/flecha-icon_ao3hw7.png" width="150px">
      </div>
      <div class="card-text">
        <p>Visualiza tus avances junto con tu <span>terapeuta</span> asignado</p>
      </div>
    </div>
  </div>
</div>

<div class="info-homepage">
  <img src="https://res.cloudinary.com/luda9/image/upload/v1662491769/development/vector6_wwbf2c.png" alt="" class="estrella1">
  <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector8_re2otp.png" alt="" class="estrella2">
  <img src="https://res.cloudinary.com/luda9/image/upload/v1662491770/development/vector7_s6xiy7.png" alt="" class="estrella3">
  <div class="ra-info">
    <div class="ra-info-container">
      <p class="ra-info-title">FACILITADOR DEL APRENDIZAJE</p>
      <p>¡<span>Rápido Aprendo</span>, Plataforma Educativa que mejora el aprendizaje de los niños de forma innovadora!</p>
      <p>Utilizamos el <span>micro-learning</span> como estrategía de aprendizaje para desarrollar nuestros contenidos.</p>
      <p>Cada video simplifica temas complejos a traves de <span>pequeñas píldoras</span> de información en menos de 5 minutos.</p>
      <p>Los alumnos asimilan el conocimiento y desarrollan <span>autonomía y pensamiento crítico</span>.</p>
    </div>
  </div>
  <div class="kid-image">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1662480985/development/ra-kid_aewlep.png" alt="">
  </div>
</div>

<footer>

  <div class="rapido-aprendo">
    <div class="rapido-aprendo-title">
      <h3>Rápido Aprendo</h3>
    </div>
    <div class="footer-text">
      <div class="footer-info">
        <p>Rápido aprendo, es una plataforma con fines de demostrar lo aprendido durante el bootcamp de Le Wagon batch 969 en Septiembre del 2022</p>
      </div>
      <div class="footer-rights">
        <p>&copy 2022 Rápido Aprendo – Todos los derechos reservados</p>
      </div>
      <div class="contactanos">
        <a href="mailto:contacto@rapidoaprendo.me?subject=Hola">Contactanos</a>
      </div>
    </div>
  </div>

  <div class="creadores">
    <div class="creadores-title">
      <h3>Creadores</h3>
    </div>
    <div class="creador">
      <div class="datos-creador">
        <h3>Daniel Santillan</h3>
        <p>Jr Full Stack Developer</p>
      </div>
      <div class="favicons">
        <a href="https://www.linkedin.com/in/luis-daniel-maga%C3%B1a-santillan-49539a236/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
        <a href="https://github.com/luda9" target="_blank"><i class="fa-brands fa-github"></i></a>
        <a href="mailto:ldms99@hotmail.com?subject=Hola" target="_blank"><i class="fa-regular fa-envelope"></i></a>
        <a href="https://www.luda.com" target="_blank"><i class="fa-solid fa-folder"></i></a>
      </div>
    </div>
    <div class="creador">
      <div class="datos-creador">
        <h3>Hiram Ramirez</h3>
        <p>Jr Full Stack Developer</p>
      </div>
      <div class="favicons">
        <i class="fa-brands fa-linkedin"></i>
        <i class="fa-brands fa-github"></i>
        <i class="fa-regular fa-envelope"></i>
        <i class="fa-solid fa-folder"></i>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_app-navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fondo-navbar">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag "https://res.cloudinary.com/luda9/image/upload/v1662653568/development/rapidoaprendo_xpql39.png", class:"ra-logo" %>
    <% end %>
  <ul class="botones-navbar ">
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Tareas", tasks_path %></li>
      <li><%= link_to "Flashcards", my_flashcards_path %></li>
  </ul>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <% unless current_user.photo.attached? %>
            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png", class: "avatar dropdown-toggle foto-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle foto-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style:"height:40px; cursor:pointer;" %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Inicio", root_path, class: "dropdown-item" %>
              <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-5 py-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>Rápido aprendo</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% unless current_user.photo.attached? %>
                <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style:"height:40px; cursor:pointer;" %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "boton entrar" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="task-title-index">
  <h2>Tareas</h2>
</div>
<div class="task-index" data-controller="task-color-show">

  <% @tasks.each do |task| %>
      <div class="card task-color-show" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-title"><%= task.title %></h3>
          <p class="card-text"><%= task.details %></p>
          <%= link_to "Comenzar", task_path(task), class: "task-button"%>
        </div>
      </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="show-tasks-container">
  <div class="show-task">
    <div class="show-task-title">
      <%= @task.title %>
      <div>
        <img class="logo-leyendo" src="https://res.cloudinary.com/luda9/image/upload/v1662671032/development/logoLeyendo_tcgbc9.gif" alt="">
      </div>
    </div>
    <div class="video-div">
      <video controls>
        <source src="<%= @task.video %>" type="video/mp4">
      </video>
    </div>
    <div class="show-tasks-buttons">
      <div class="show-tasks-flashcards-button">
        <%= link_to "Flashcards", task_flashcards_path(@task), class: "task-button" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="mt-4">Tus datos</h2>
<div class="show-user-page">
    <div class="show-user-box">
      <div class="show-avatar">
        <% unless current_user.photo.attached? %>
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" %>
        <% else %>
          <%= cl_image_tag @user.photo.key %>
        <% end %>
      </div>
      <div class="show-user-info">
        <h5>Nombre</h5>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.first_name %> <%= @user.last_name %></p>
        <h5>Correo</h5>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.email %></p><br>
        <%= link_to "Editar información", edit_user_registration_path, class:"boton entrar" %>
      </div>
    </div>
</div>